### ISSUE TITLE
How to call Blynk function

### ISSUE THREAD

**Issue by terzika** [khoih-prog/ESP_AT_WM_Lite#1]
Dear Khoih,

Could you be so kind to share with me how to call Blynk function in a sketch using the dynamic custom parameters entered through Configuration Portal Mode (Blynk_Token, Blynk_Server &Blynk_port).

BR,
Terzika

**Comment by terzika** [comment]
This is my sketch on Mega 2560 and I want to use ssid, pass, and Blynk parameters entered through Configuration Portal

#define BLYNK_PRINT Serial
#define BLYNK_DEBUG
#include <ESP8266_Lib.h>
#include <BlynkSimpleShieldEsp8266.h>
#define ESP8266_BAUD 115200

char auth[] = "xxxxxxxxxxxxxxxxxxxxxxxxxx";                          

char ssid[] = "xxxxx";
char pass[] = "xxxxxx";
char server[] = "blynk-cloud.com";
uint16_t  port  = 8080;

#define EspSerial Serial3
ESP8266 wifi(&EspSerial);
BlynkTimer timer;


void setup() {
   
  timer.setInterval(15000L, SendtoBlynk);
  timer.setInterval(60000L, CheckConnection); 
    
  Serial.begin(115200);
  EspSerial.begin(ESP8266_BAUD);
   Blynk.config(wifi, auth, server, port);
 
  if (Blynk.connectWiFi(ssid, pass)) {
  
      Blynk.connect();
 }
   if(Blynk.connected()){  
      Serial.println("Connected in Setup"); 
    } 

} // ***********************End Setup*************************


void loop() {
 
  if(Blynk.connected()) {
    Blynk.run();
  } 
  timer.run();
}//****************** End Loop************



  
void CheckConnection(){                               
  
  if(!Blynk.connected()){
    Serial.println("Not connected to Blynk server"); 
    Blynk.connect();  
    if(Blynk.connected()){
        Serial.println("Reconnected to Blynk server");   
     }
  
        
  }
} //***************End CheckConnection()*************************


 
 void BlinkBlynk() {
  Bla, Bla, Bla
 } // **************End BlinkBlynk************

**Comment by khoih-prog** [comment]
Hi @terzika 

You are using the wrong library for your current purpose. You can achieve what you'd like with this lib, but have to write extra code.

It's better to use this library for your Mega to connect to Blynk

[Bynk-Wifimanager For Mega](https://community.blynk.cc/t/blynk-wifimanager-for-mega-teensy-sam-due-samd-stm32-boards-running-esp8266-at-shields/43688)

[Blynk_Esp8266AT_WM](https://github.com/khoih-prog/Blynk_Esp8266AT_WM)
